// This file was autogenerated by calcdeps.py
goog.addDependency("../../soyutils_usegoog.js", ['soy', 'soy.StringBuilder'], ['goog.dom', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency("../../../../app/project/plugins/drivers/drvtlm3/drvtlm3.js", ['drvtlm3.Plugin'], ['drvtlm3.view']);
goog.addDependency("../../../../app/project/plugins/drivers/drvtlm3/scripts/controller.js", ['drvtlm3.controller'], ['drvtlm3.model']);
goog.addDependency("../../../../app/project/plugins/drivers/drvtlm3/scripts/fixture.js", ['drvtlm3.fixture'], ['goog.array']);
goog.addDependency("../../../../app/project/plugins/drivers/drvtlm3/scripts/model.js", ['drvtlm3.model'], ['drvtlm3.fixture']);
goog.addDependency("../../../../app/project/plugins/drivers/drvtlm3/scripts/view.js", ['drvtlm3.view'], ['drvtlm3.controller', 'drvtlm3.model']);
goog.addDependency("../../../emax/goog/app.js", [], []);
goog.addDependency("../../../emax/goog/constants.js", ['constants'], []);
goog.addDependency("../../../emax/goog/environment.js", ['environment'], ['goog.uri.utils', 'goog.Uri']);
goog.addDependency("../../../emax/goog/router.js", ['router'], ['environment', 'goog.uri.utils', 'goog.Uri']);
goog.addDependency("../../../emax/goog/tools.js", ['tools'], []);
goog.addDependency("../../../../app/project/plugins/drivers/drvtlm3/drvtlm3.tpl_ru.js", ['drvtlm3.locale'], ['soy', 'soy.StringBuilder']);
